### ISSUE TITLE
BoolOption.isSet true by default

### ISSUE THREAD

**Issue by beltex** [jatoben/CommandLine#24]
I was wondering, shouldn’t `BoolOption.isSet` **_not_** be true by default for consistency with other options? The reason I ask is that it thwarts common patterns for trying to determine which options are set after parsing.

```swift
var CLIOptions = [Option]()

// Create options, parse, etc., ...

// This doesn’t currently work because of BoolOption (since its true by default)
let flagsOn = CLIOptions.filter { $0.isSet }

// A work around
let isSetNonBoolOptions = CLIOptions.filter { $0.isSet == true &&
                                              $0 as? BoolOption == nil }
let isSetBoolOptions = CLIOptions.filter { $0 as? BoolOption != nil }
                                 .map    { $0 as! BoolOption        }
                                 .filter { $0.value == true         }
```

Is there a better way to go about this? Love to hear what you think!

**Comment by brunophilipe** [comment]
```

**Comment by jatoben** [comment]
Actually I considered `isSet` to be a pretty nasty wart when I wrote it, and it looks even uglier now. I'd love to get rid of it, but there's not a way to override a method with one that returns a more specific type. For example, this code:

```swift
public class Option {
  public var value: Any? { return nil; }
}

public class IntOption: Option {
  override public var value: Int? { return 1 } 
}
```

makes the compiler complain _Property 'value' with type 'Int?' cannot override a property with type 'Any?'_. Attempting to use protocols result in a similar error:

```swift
protocol OptionProto {
  var value: Any? { get }
}

public class IntOption: OptionProto {
  public var value: Int? { return 1 }
}
```

_Type 'IntOption' does not conform to protocol 'OptionProto'_.

The parser shoves all the options into an `[Option]` array (thus losing type information), but to implement required options, it needs to check each one to see if it has been set. It can't check the `value` property  though, because it's not in the `Option` base class due to the problem described above. The only way to put it there would be for `value` to return `Any?`, but then you'd have to cast  `StringOption.value` to `String?`, `IntOption.value` to `Int?`, etc. — a far worse situation IMO.

As @brunophilipe mentioned, `isSet` doesn't make a lot of sense for BoolOptions and CounterOptions, since their `value` property isn't an optional — if they're omitted from the command line, the value is `false` or `0`. It doesn't make sense to have a required BoolOption; it'd just always be `true`.

Unless you know of a good workaround (which would be great!), I consider `isSet` to be a implementation detail, and it should probably be marked `private`. I've never stored options in an array though, which causes the same problem that the parser has. I just use their values to initialize my app's classes, structs, etc., and if `nil` isn't a reasonable value, I mark the option as required. Do you have an example of where you'd use your pattern in real code?

**Comment by jatoben** [comment]
@beltex It looks like you use this approach (iterating over an array of options to see which ones have been set) in [SMCKit](https://github.com/beltex/SMCKit), is that right? Looking at the code, this is a pretty reasonable use case and something CommandLine should probably do, even though I'd rather there were a better way around the type ugliness.

I went ahead and made `wasSet` a public property in #26. If there's a way to avoid the annoying type issues in a future Swift release, all the declarations can just be deleted from the subclasses.

**Comment by beltex** [comment]
> It looks like you use this approach (iterating over an array of options to see which ones have been set) in SMCKit, is that right? Looking at the code, this is a pretty reasonable use case and something CommandLine should probably do,

@jatoben Thats the one! Thank you so much for taking a look, really appreciate it! :)

> I went ahead and made wasSet a public property in #26. If there's a way to avoid the annoying type issues in a future Swift release, all the declarations can just be deleted from the subclasses.

Sounds good!

A totally minor follow up to this. What do you think about making `CommandLine._options` public given this use case? Saves the client from having to make an array, using the `addOptions()` method that takes a variadic parameter instead.
